### ISSUE TITLE
[Bug]: Changing shipping details after shipments are loaded

### ISSUE THREAD

**Issue by rafalkosla101** [vuestorefront/spree#168] opened 2022-03-22 15:30 UTC
### Expected Behavior

User cannot change provided shipping details after clicking "select shipping method" since shipping methods are based on provided data which could lead to errors

### Actual Behavior

User can freely change any provided details

### What version of Spree integration are you using?

1.3.0

### What version of Node.js are you using?

14.18.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by letelete** [comment] 2022-03-23 07:48
Duplicate of #165 

I will assign you to the original issue and link the PR.

**Closed by letelete** 2022-03-23 07:48 UTC
Labels: bug
